eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8766
  
spring:
  application:
    name: tcloud-user-hi
  aop:
    auto: true
    proxy-target-class: true